---
- hosts: node
  remote_user: root
  vars:
    kube_version: 1.18.6-0
  tasks:
    - name: prepare env
      script: ../bin/pre-setup.sh
    - name: install kubeadm,kubelet
      yum: 
        name: ['kubeadm-{{kube_version}}','kubelet-{{kube_version}}']
    - name: start kubelt
      shell: systemctl enable kubelet && systemctl start kubelet
    - name: join cluster
      shell: kubeadm join 192.168.0.140:6443 --token rqd33w.aenbeoulh3hk0m32     --discovery-token-ca-cert-hash sha256:72d11c594ded9aa67b7c545af9006d50efd124cd499ea141b6e594bc47fe6f2a