---
- hosts: master
  remote_user: root
  tasks:
  - name: unarchive
    unarchive: 
      src: ../bin/helm-v3.2.0-rc.1-linux-amd64.tar.gz
      dest: /opt/
      copy: yes
  - name: install helm
    shell: mv /opt/linux-amd64/helm /bin/
