---
- hosts: "{{ hosts | default('all') }}"
  remote_user: root
  tasks:
    - name: install dependencies
      yum: name={{item}} state=present
      with_items:
        - yum-utils
        - device-mapper-persistent-data
        - lvm2
    - name: config yum repo
      shell: yum-config-manager --add-repo https://mirrors.ustc.edu.cn/docker-ce/linux/centos/docker-ce.repo
    
    - name: install docker
      yum: name=docker-ce-18.09.2 state=present

    - name: start docker
      shell: systemctl enable docker && systemctl start docker 