---
## 从香港服务器拉取镜像上传到华为云
- hosts: hongkong
  remote_user: root
  tasks:
    - name: install dependencies
      yum:  name={{item}} state=present
      with_items:
        - yum-utils
        - device-mapper-persistent-data
        - lvm2
    - name: add repo
      shell: yum-config-manager --add-repo https://mirrors.ustc.edu.cn/docker-ce/linux/centos/docker-ce.repo
    - name: install docker
      yum: name=docker-ce-18.09.2 state=present
    - name: start docker
      shell: systemctl enable docker && systemctl start docker 
    - name: log in  Software Repository for Container
      shell: docker login -u cn-north-4@EBC2A0BEU4UI3O4QBDAR -p 8ac62f1b3e67fc6645ee410906a83f66326d7b9ebcb00cb90a65d74a1e1c5276 swr.cn-north-4.myhuaweicloud.com
    - name: docker pull from gc.io
      script: ../bin/load_images.sh
